// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Balance is the predicate function for balance builders.
type Balance func(*sql.Selector)

// BalanceOrErr calls the predicate only if the error is not nit.
func BalanceOrErr(p Balance, err error) Balance {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
