// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BalancesColumns holds the columns for the "balances" table.
	BalancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account", Type: field.TypeString},
		{Name: "block_number", Type: field.TypeString},
		{Name: "balance", Type: field.TypeString},
	}
	// BalancesTable holds the schema information for the "balances" table.
	BalancesTable = &schema.Table{
		Name:       "balances",
		Columns:    BalancesColumns,
		PrimaryKey: []*schema.Column{BalancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "balance_account",
				Unique:  false,
				Columns: []*schema.Column{BalancesColumns[1]},
			},
			{
				Name:    "balance_account_block_number",
				Unique:  true,
				Columns: []*schema.Column{BalancesColumns[1], BalancesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BalancesTable,
	}
)

func init() {
}
